---
title: Getting started with the Camera Module
hero_image: images/banner.png
description: Take pictures and video with the Raspberry Pi Camera Module and Python
listed: true
copyedit: true
version: 4
last_tested: 2018-05-13
steps:
- title: Introduction
- title: What you will need
- title: Connect the Camera Module
- title: How to control the Camera Module via the command line
  completion:
  - engaged
- title: How to control the Camera Module with Python code
- title: Take still pictures with Python code
- title: Record video with Python code
- title: How to change the image settings and add image effects
  completion:
  - internal
- title: What next?
