title: Getting started with the camera module
hero_image: images/banner.png
description: Get started with the Raspberry Pi camera module, using Python and picamera
listed: true
copyedit: true
version: 4
last_tested: 2018-05-13
steps: 
- title: Introduction
- title: What you will need
- title: Connect the camera module
- title: Using the camera
- title: Controlling the camera with Python
- title: Still pictures
- title: Recording video
- title: Effects
- title: What next?