---
title: कॅमेरा मॉड्यूलसह सुरु करणे
hero_image: images/banner.png
description: रास्पबेरी पाई कॅमेरा मॉड्यूल आणि पायथनसह चित्रे आणि व्हिडिओ काढा
listed: true
copyedit: true
version: 4
last_tested: 2018-05-13
steps:
- title: परिचय
- title: आपल्याला कशाची गरज असेल
- title: कॅमेरा मॉड्यूल कनेक्ट करा
- title: कमांड लाइनद्वारे कॅमेरा मॉड्यूल कसे नियंत्रित करावे
  completion:
  - engaged
- title: पायथन कोडसह कॅमेरा मॉड्यूल कसे नियंत्रित करावे
- title: पायथन कोडसह स्थिर चित्रे काढा
- title: पायथन कोडसह व्हिडिओ रेकॉर्ड करा
- title: चित्र सेटिंग्ज कशी बदलायची आणि चित्र परिणाम कसा जोडावा
  completion:
  - internal
- title: पुढे काय?
