---
title: कैमरा मॉड्यूल के साथ शुरुआत करना
hero_image: images/banner.png
description: Raspberry Pi कैमरा मॉड्यूल और Python के साथ चित्र और वीडियो लें
listed: true
copyedit: true
version: 4
last_tested: 2018-05-13
steps:
- title: भूमिका
- title: आपको किन चीजों की आवश्यकता होगी
- title: कैमरा मॉड्यूल कनेक्ट करें
- title: कमांड लाइन के माध्यम से कैमरा मॉड्यूल को कैसे नियंत्रित किया जाए
  completion:
  - engaged
- title: Python कोड के साथ कैमरा मॉड्यूल को कैसे नियंत्रित किया जाए
- title: Python कोड के साथ स्थिर तस्वीरें ले
- title: Python कोड के साथ वीडियो रिकॉर्डिंग
- title: छवि सेटिंग्स कैसे बदलें और छवि प्रभाव जोड़ें
  completion:
  - internal
- title: आगे क्या?
