---
title: Getting started with the Camera Module
hero_image: images/banner.png
description: RaspberryPiカメラモジュールとPythonで写真とビデオを撮る
listed: true
copyedit: true
version: 4
last_tested: 2018-05-13
steps:
  - 
    title: はじめに
  - 
    title: 必要なもの
  - 
    title: カメラモジュールを接続する
  - 
    title: コマンドラインでカメラモジュールをコントロールする方法
  - 
    title: Pythonコードでカメラモジュールをコントロールする方法
  - 
    title: Pythonコードで静止画を撮る
  - 
    title: Pythonコードでビデオを録画する
  - 
    title: How to change the image settings and add image effects
  - 
    title: What next?
