---
title: Premiers pas avec le module caméra
hero_image: images/banner.png
description: Capturer des images et des vidéos avec le module caméra du Raspberry
  Pi et Python
listed: true
copyedit: true
version: 4
last_tested: 2018-05-13
steps:
- title: Introduction
- title: Ce dont tu auras besoin
- title: Connecter le module caméra
- title: Comment contrôler le module caméra via la ligne de commande
  completion:
  - engaged
- title: Comment contrôler le module caméra avec du code Python
- title: Capturer des images fixes avec du code Python
- title: Enregistrer des vidéos avec du code Python
- title: Comment modifier les paramètres d'image et ajouter des effets d'image
  completion:
  - internal